{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clearmlServing.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "clearmlServing.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations: {{- .Values.serviceAccount.annotations | toYaml | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}

